apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fleet
  namespace: argofleet
spec: 
  sourceRepos:
  - "https://andidroid.github.io/gorouting-gitops/"
  destinations:
    - server: "https://kubernetes.default.svc"
      namespace: argofleet
