kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "routingservice.fullname" . }}
  labels:
    {{- include "routingservice.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "routingservice.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{ .Values.networkPolicy.policyTypes }}
  ingress:
    {{if has "ingress" .Values.networkPolicy.policyTypes }}
      {{ .Values.networkPolicy.ingress }}
    {{ end }}
  egress:
    {{if has "egress" .Values.networkPolicy.policyTypes }}
      {{ .Values.networkPolicy.egress }}
    {{ end }}