apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: fleet
  name: routingservice-hpa
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: routingservice-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

