{{- define "servicelibrary.configmap.tpl" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "servicelibrary.fullname" . }}
data: {}
{{- end -}}

{{- define "servicelibrary.configmap" -}}
{{- include "servicelibrary.util.merge" (append . "servicelibrary.configmap.tpl") -}}
{{- end -}}