{{- define "servicelibrary.networkpolicy.tpl" -}}
{{- if .Values.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "servicelibrary.fullname" . }}
  labels:
    {{- include "servicelibrary.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "servicelibrary.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{ .Values.networkPolicy.policyTypes }}
  ingress:
    {{if has "ingress" .Values.networkPolicy.policyTypes }}
      {{ .Values.networkPolicy.ingress }}
    {{ end }}

  egress:
    {{if has "egress" .Values.networkPolicy.policyTypes }}
      {{ .Values.networkPolicy.egress }}
    {{ end }}
{{ end }}
{{ end }}

{{- define "servicelibrary.networkpolicy" -}}
{{- include "servicelibrary.util.merge" (append . "servicelibrary.networkpolicy.tpl") -}}
{{- end -}}